"""empty message

Revision ID: 1172aca44a58
Revises: e786e6c04d77
Create Date: 2026-07-16 17:46:41.696783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1172aca44a58"
down_revision: Union[str, Sequence[str], None] = "e786e6c04d77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chat_messages", "content", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "chats",
        "ai_models",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chats",
        "ai_models",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    op.alter_column("chat_messages", "content", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
