"""empty message

Revision ID: 1765b18539be
Revises: a3fadc78b033
Create Date: 2026-07-19 15:00:28.013988

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1765b18539be'
down_revision: Union[str, Sequence[str], None] = 'a3fadc78b033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_chat_messages', 'path',
               existing_type=sqlalchemy_utils.types.ltree.LtreeType(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_chat_messages', 'path',
               existing_type=sqlalchemy_utils.types.ltree.LtreeType(),
               nullable=False)
    # ### end Alembic commands ###
