"""empty message

Revision ID: 4b1ebc3b4eae
Revises: 1765b18539be
Create Date: 2026-07-29 18:44:13.315330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4b1ebc3b4eae"
down_revision: Union[str, Sequence[str], None] = "1765b18539be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_chat_members",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["project_chats.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("chat_id", "user_id"),
    )
    op.drop_constraint(
        op.f("chat_members_chat_id_fkey"), "chat_members", type_="foreignkey"
    )
    op.create_foreign_key(None, "chat_members", "chats", ["chat_id"], ["chat_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("chat_members_chat_id_fkey"),
        "chat_members",
        "project_chats",
        ["chat_id"],
        ["chat_id"],
    )
    op.drop_table("project_chat_members")
    # ### end Alembic commands ###
