"""empty message

Revision ID: a3fadc78b033
Revises: 1172aca44a58
Create Date: 2026-07-19 14:53:07.818275

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fadc78b033'
down_revision: Union[str, Sequence[str], None] = '1172aca44a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'path',
               existing_type=sqlalchemy_utils.types.ltree.LtreeType(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'path',
               existing_type=sqlalchemy_utils.types.ltree.LtreeType(),
               nullable=False)
    # ### end Alembic commands ###
