"""Add name field for AIModels

Revision ID: c24c889fc351
Revises: 5cdfe3085f18
Create Date: 2026-07-04 14:37:22.473075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24c889fc351'
down_revision: Union[str, Sequence[str], None] = '5cdfe3085f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('name', sa.String(length=100), nullable=False))
    op.alter_column('ai_models', 'display_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_models', 'display_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('ai_models', 'name')
    # ### end Alembic commands ###
