"""empty message

Revision ID: e786e6c04d77
Revises: 5e781a049e4d
Create Date: 2026-07-13 12:15:58.304934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e786e6c04d77"
down_revision: Union[str, Sequence[str], None] = "5e781a049e4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=100), nullable=False))
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###
