"""empty message

Revision ID: f710a8089d90
Revises: 1d518aaa15a7
Create Date: 2026-08-10 21:34:45.587175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f710a8089d90"
down_revision: Union[str, Sequence[str], None] = "1d518aaa15a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_members", sa.Column("is_owner", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_members", "is_owner")
    # ### end Alembic commands ###
